# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-test',
                'doc_host': 'https://jason-drury.github.io',
                'git_url': 'https://github.com/jason-drury/nbdev-test',
                'lib_path': 'nbdev_test'},
  'syms': { 'nbdev_test.core': {'nbdev_test.core.foo': ('core.html#foo', 'nbdev_test/core.py')},
            'nbdev_test.core_functions': { 'nbdev_test.core_functions.read_image': ( 'core_functions.html#read_image',
                                                                                     'nbdev_test/core_functions.py'),
                                           'nbdev_test.core_functions.say_hello': ( 'core_functions.html#say_hello',
                                                                                    'nbdev_test/core_functions.py')}}}
