# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core_functions.ipynb.

# %% auto 0
__all__ = ['read_image', 'say_hello', 'HelloSayer']

# %% ../nbs/00_core_functions.ipynb 4
def read_image(filename): 
    "Read individual image from file and return image and metadata."
    image = ''
    metadata = ''
    return image, metadata

# %% ../nbs/00_core_functions.ipynb 5
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_core_functions.ipynb 10
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to
        
    def say(self):
        "Do the saying"
        return say_hello(self.to)
