# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core_functions.ipynb.

# %% auto 0
__all__ = ['read_image', 'say_hello']

# %% ../nbs/00_core_functions.ipynb 3
def read_image(filename): 
    "Read individual image from file and return image and metadata."
    image = ''
    metadat = ''
    return image, metadata

# %% ../nbs/00_core_functions.ipynb 4
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
