# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core_functions.ipynb.

# %% auto 0
__all__ = ['read_image', 'say_hello', 'HelloSayer', 'all']

# %% ../nbs/00_core_functions.ipynb 4
def read_image(filename): 
    "Read individual image from file and return image and metadata."
    image = ''
    metadata = ''
    return image, metadata

# %% ../nbs/00_core_functions.ipynb 5
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_core_functions.ipynb 10
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to
        
    def say(self):
        "Do the saying"
        return say_hello(self.to)

# %% ../nbs/00_core_functions.ipynb 14
def all(a, # Input array or object that can be converted to an array.
        axis:int|tuple|None=None, # Axis or axes along which a logical AND reduction is performed (default: all).
        out:np.ndarray|None=None, # Alternate output array in which to place the result.
        keepdims:bool=np._NoValue, # Leave reduced one-dimensional axes in the result?
        where=np._NoValue, # Elements to include in reduction. See `numpy.ufunc.reduce` for details. New in version 1.20.0.
        ) -> np.ndarray|bool: # A new boolean or array, or a reference to `out` if its specified.
    "Test whether all array elements along a given axis evaluate to `True`."
    ...
